
title: Ryan Ngo
author: Ryan Ngo
description: Personal Website
baseurl: ""
url: https://RyanVNgo.github.io

github: https://github.com/RyanVNgo
linkedin: https://www.linkedin.com/in/ryanvngo/
email: vanryan711@gmail.com

projects-imgs-dir: /assets/images/projects/
posts-imgs-dir: /assets/images/posts/

docs:
  - title: home
    url: /index.html

  - title: projects
    url: /pages/projects.html

  - title: posts 
    url: /pages/posts.html

  - title: reading 
    url: /pages/reading.html

  # - title: about
  #   url: /pages/about.html

collections_dir: collections
collections:
  projects:
    output: true

  readings:
    output: true

sass:
  style: compressed

excerpt_separator: <!-- more -->

plugins:
  - jekyll-octicons
